// src/types.ts

export interface Squad {
  id: number;
  name: string;
  member_count: number;
}

export interface Absence {
  id?: number; // Optional as it's auto-generated by DB
  squad_id: number;
  member_name: string;
  start_date: string; // YYYY-MM-DD
  end_date: string; // YYYY-MM-DD
}

export interface WeekCapacity {
  squadName: string;
  weekId: string; // e.g., "2025-W28"
  percentageAbsence: number;
  alert: boolean;
}
